openapi: 3.1.0
info:
  title: openapi
  version: 1.0.0
paths:
  '/api/accounts':
    post:
      summary: Create an Account
      operationId: Create an Account
      description: ''
      tags:
        - ''
      responses:
        '200':
          description: ''
      requestBody:
        $ref: '#/components/requestBodies/create_an_account'
  '/api/currencies':
    post:
      summary: Create Currency
      operationId: Create Currency
      description: ''
      tags:
        - ''
      responses:
        '200':
          description: ''
      requestBody:
        $ref: '#/components/requestBodies/create_currency'
  '/api/ledgers':
    post:
      summary: Create a Ledger
      operationId: Create a Ledger
      description: ''
      tags:
        - ''
      responses:
        '200':
          description: ''
      requestBody:
        $ref: '#/components/requestBodies/create_a_ledger'
  '/health':
    get:
      summary: Health Check
      operationId: Health Check
      description: ''
      tags:
        - ''
      responses:
        '200':
          description: ''
servers: 
  - url: "{{server_url}}"
    description: KitLedger's server URL van vary depending on the deployment method, such as Cloud or Self Hosted. Please consult with your IT administrator or the KitLedger team to find your URL.
security:
  - {}
components:
  schemas:
    create_an_account:
      type: object
      properties:
        ref_id:
          type: string
        alt_id:
          type: string
        name:
          type: string
        balance_type:
          type: string
        ledger_id:
          type: string
        active:
          type: boolean
        meta:
          type: object
          properties:
            description:
              type: string
    create_currency:
      type: object
      properties:
        name:
          type: string
        symbol:
          type: string
        iso_code:
          type: string
        precision:
          type: number
        decimal_separator:
          type: string
        thousands_separator:
          type: string
    create_a_ledger:
      type: object
      properties:
        name:
          type: string
          description: 'Ledger name'
        ref_id:
          type: string
        description:
          type: string
        currency_id:
          type: string
  requestBodies:
    create_an_account:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/create_an_account'
      description: ''
      required: true
    create_currency:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/create_currency'
      description: ''
      required: true
    create_a_ledger:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/create_a_ledger'
      description: ''
      required: true
  securitySchemes: {}
